package media

import (
	"bytes"
	"context"
	"crypto"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/pion/interceptor"
	"github.com/pion/interceptor/pkg/intervalpli"
	"github.com/pion/webrtc/v4"
	"go.opentelemetry.io/otel"
	"stream.place/streamplace/pkg/aigateway"
	"stream.place/streamplace/pkg/aqtime"
	"stream.place/streamplace/pkg/atproto"
	"stream.place/streamplace/pkg/bus"
	c2patypes "stream.place/streamplace/pkg/c2patypes"
	"stream.place/streamplace/pkg/config"
	"stream.place/streamplace/pkg/gstinit"
	"stream.place/streamplace/pkg/model"
	"stream.place/streamplace/pkg/streamplace"

	"stream.place/streamplace/pkg/log"

	"github.com/piprate/json-gold/ld"

	irohStreamplace "stream.place/streamplace/pkg/iroh/generated/iroh_streamplace"

	_ "stream.place/streamplace/pkg/streamplacedeps"
)

const CertFile = "cert.pem"
const SegmentsDir = "segments"

var StreamplaceMetadata = "place.stream.metadata"

type MediaManager struct {
	cli                 *config.CLI
	hlsRunning          map[string]*M3U8
	hlsRunningMut       sync.Mutex
	httpPipes           map[string]io.Writer
	httpPipesMutex      sync.Mutex
	newSegmentSubs      []chan *NewSegmentNotification
	newSegmentSubsMutex sync.RWMutex
	model               model.Model
	bus                 *bus.Bus
	atsync              *atproto.ATProtoSynchronizer
	webrtcAPI           *webrtc.API
	webrtcConfig        webrtc.Configuration
	transcriptStore     *aigateway.TranscriptStore
	audioWindowAnchors  map[string]map[int64]aigateway.AudioWindowAnchorUpdate
	audioAnchorsMu      sync.RWMutex
}

type NewSegmentNotification struct {
	Segment  *model.Segment
	Data     []byte
	Metadata *SegmentMetadata
	Local    bool
}

func RunSelfTest(ctx context.Context) error {
	gstinit.InitGST()
	return SelfTest(ctx)
}

func MakeMediaManager(ctx context.Context, cli *config.CLI, signer crypto.Signer, mod model.Model, bus *bus.Bus, atsync *atproto.ATProtoSynchronizer) (*MediaManager, error) {
	gstinit.InitGST()
	err := SelfTest(ctx)
	if err != nil {
		return nil, fmt.Errorf("error in gstreamer self-test: %w", err)
	}

	m := &webrtc.MediaEngine{}
	// Create a InterceptorRegistry. This is the user configurable RTP/RTCP Pipeline.
	// This provides NACKs, RTCP Reports and other features. If you use `webrtc.NewPeerConnection`
	// this is enabled by default. If you are manually managing You MUST create a InterceptorRegistry
	// for each PeerConnection.
	i := &interceptor.Registry{}

	// Register a intervalpli factory
	// This interceptor sends a PLI every 3 seconds. A PLI causes a video keyframe to be generated by the sender.
	// This makes our video seekable and more error resilent, but at a cost of lower picture quality and higher bitrates
	// A real world application should process incoming RTCP packets from viewers and forward them to senders
	intervalPliFactory, err := intervalpli.NewReceiverInterceptor()
	if err != nil {
		return nil, fmt.Errorf("failed to create intervalpli factory: %w", err)
	}
	i.Add(intervalPliFactory)

	if err := m.RegisterCodec(webrtc.RTPCodecParameters{
		RTPCodecCapability: webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeH264, ClockRate: 90000, Channels: 0, SDPFmtpLine: "", RTCPFeedback: nil},
		PayloadType:        102,
	}, webrtc.RTPCodecTypeVideo); err != nil {
		return nil, err
	}
	if err := m.RegisterCodec(webrtc.RTPCodecParameters{
		RTPCodecCapability: webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeOpus, ClockRate: 48000, Channels: 0, SDPFmtpLine: "", RTCPFeedback: nil},
		PayloadType:        111,
	}, webrtc.RTPCodecTypeAudio); err != nil {
		return nil, err
	}

	// Use the default set of Interceptors
	if err = webrtc.RegisterDefaultInterceptors(m, i); err != nil {
		return nil, fmt.Errorf("failed to register default interceptors: %w", err)
	}

	// Create the API object with the MediaEngine
	api := webrtc.NewAPI(webrtc.WithMediaEngine(m), webrtc.WithInterceptorRegistry(i))

	// Prepare the configuration
	config := webrtc.Configuration{
		ICEServers: []webrtc.ICEServer{
			{
				URLs: []string{"stun:stun.l.google.com:19302"},
			},
		},
	}
	return &MediaManager{
		cli:             cli,
		hlsRunning:      map[string]*M3U8{},
		httpPipes:       map[string]io.Writer{},
		model:           mod,
		bus:             bus,
		atsync:          atsync,
		webrtcAPI:       api,
		webrtcConfig:    config,
		transcriptStore: aigateway.NewTranscriptStore(),
		audioWindowAnchors: map[string]map[int64]aigateway.AudioWindowAnchorUpdate{},
	}, nil
}

func (mm *MediaManager) GetTranscriptSegments(streamer string) []aigateway.TranscriptSegment {
	return mm.transcriptStore.GetSegments(streamer)
}

func (mm *MediaManager) setAudioWindowAnchor(streamer string, anchor aigateway.AudioWindowAnchorUpdate) {
	ctx := context.Background()
	if streamer == "" || anchor.AudioWindowSeq <= 0 || anchor.MediaWindowStartMS < 0 {
		log.Debug(ctx, "setAudioWindowAnchor: skipping invalid anchor",
			"streamer", streamer,
			"seq", anchor.AudioWindowSeq,
			"start_ms", anchor.MediaWindowStartMS,
		)
		return
	}
	mm.audioAnchorsMu.Lock()
	defer mm.audioAnchorsMu.Unlock()
	if _, ok := mm.audioWindowAnchors[streamer]; !ok {
		mm.audioWindowAnchors[streamer] = map[int64]aigateway.AudioWindowAnchorUpdate{}
	}
	mm.audioWindowAnchors[streamer][anchor.AudioWindowSeq] = anchor

	// Retain a bounded number of anchors per streamer.
	if len(mm.audioWindowAnchors[streamer]) > 2048 {
		cutoff := anchor.AudioWindowSeq - 2048
		for seq := range mm.audioWindowAnchors[streamer] {
			if seq <= cutoff {
				delete(mm.audioWindowAnchors[streamer], seq)
			}
		}
	}
}

func (mm *MediaManager) getAudioWindowAnchor(streamer string, seq int64) (aigateway.AudioWindowAnchorUpdate, bool) {
	mm.audioAnchorsMu.RLock()
	defer mm.audioAnchorsMu.RUnlock()
	m, ok := mm.audioWindowAnchors[streamer]
	if !ok {
		return aigateway.AudioWindowAnchorUpdate{}, false
	}
	a, ok := m[seq]
	return a, ok
}

func (mm *MediaManager) rebaseTranscriptEvent(streamer string, event *aigateway.TranscriptEvent) {
	if event == nil || event.Timing == nil {
		return
	}
	if event.Timing.AudioWindowSeq <= 0 {
		return
	}
	// If the producer explicitly declares the timebase as audio-window relative, rebase.
	// Otherwise, allow a best-effort rebase when the producer provides an audio_window_seq
	// and the segment timestamps look relative (small values).
	relative := event.Timing.Timebase == "audio_window_ms"
	if !relative {
		minStart := int64(1 << 62)
		maxEnd := int64(0)
		for i := range event.Segments {
			seg := event.Segments[i]
			if seg.StartMS < minStart {
				minStart = seg.StartMS
			}
			if seg.EndMS > maxEnd {
				maxEnd = seg.EndMS
			}
		}
		// Heuristic: if all times are within a single short window, treat as relative.
		// Default window is 3s, but allow some slack.
		if len(event.Segments) > 0 && minStart >= 0 && maxEnd > 0 && maxEnd <= 10_000 {
			relative = true
		}
	}
	if !relative {
		return
	}
	anchor, anchorOK := mm.getAudioWindowAnchor(streamer, event.Timing.AudioWindowSeq)
	base := int64(-1)
	if anchorOK {
		base = anchor.MediaWindowStartMS
	} else if event.Timing.MediaWindowStartMS > 0 && (event.Timing.Timebase == "audio_window_ms" || event.Timing.MediaWindowStartMS > 10_000) {
		base = event.Timing.MediaWindowStartMS
	} else {
		return
	}
	if base < 0 {
		return
	}

	shiftSeg := func(seg *aigateway.TranscriptSegment) {
		seg.StartMS += base
		seg.EndMS += base
		for i := range seg.Words {
			seg.Words[i].StartMS += base
			seg.Words[i].EndMS += base
		}
	}
	for i := range event.Segments {
		shiftSeg(&event.Segments[i])
	}

	event.Timing.MediaWindowStartMS = base
	if anchorOK && anchor.MediaWindowDurMS > 0 {
		event.Timing.MediaWindowEndMS = base + anchor.MediaWindowDurMS
	}
	if anchorOK && anchor.MediaClockTimebase != "" {
		event.Timing.Timebase = anchor.MediaClockTimebase
	} else {
		event.Timing.Timebase = "streamplace_running_time_ms"
	}
}

func (mm *MediaManager) HandleData(node *irohStreamplace.PublicKey, data []byte) {
	r := bytes.NewReader(data)
	ctx := context.Background()
	err := mm.ValidateMP4(ctx, r, true)
	if err != nil {
		log.Log(ctx, "invalid incoming segment", "error", err)
	}
}

// replacement for os.Pipe that works on windows
func (mm *MediaManager) HTTPPipe() (string, io.ReadCloser, func(), error) {
	uu, err := uuid.NewV7()
	if err != nil {
		return "", nil, nil, err
	}
	mm.httpPipesMutex.Lock()
	defer mm.httpPipesMutex.Unlock()
	u := fmt.Sprintf("%s/http-pipe/%s", mm.cli.OwnInternalURL(), uu.String())
	done := func() {
		mm.httpPipesMutex.Lock()
		defer mm.httpPipesMutex.Unlock()
		delete(mm.httpPipes, uu.String())
	}
	r, w := io.Pipe()
	mm.httpPipes[uu.String()] = w
	return u, r, done, nil
}

func (mm *MediaManager) GetHTTPPipeWriter(uu string) io.Writer {
	mm.httpPipesMutex.Lock()
	defer mm.httpPipesMutex.Unlock()
	return mm.httpPipes[uu]
}

// register a handler for all new segments that come in
func (mm *MediaManager) NewSegment() <-chan *NewSegmentNotification {
	ch := make(chan *NewSegmentNotification)
	mm.newSegmentSubsMutex.Lock()
	defer mm.newSegmentSubsMutex.Unlock()
	mm.newSegmentSubs = append(mm.newSegmentSubs, ch)
	return ch
}

type obj map[string]any

type StringVal struct {
	Value string `json:"@value"`
}

type ExpandedSchemaOrg []struct {
	Creator []StringVal `json:"http://purl.org/dc/elements/1.1/creator"`
	Date    []StringVal `json:"http://purl.org/dc/elements/1.1/date"`
	Title   []StringVal `json:"http://purl.org/dc/elements/1.1/title"`
}

type SegmentMetadata struct {
	StartTime             aqtime.AQTime
	Title                 string
	Creator               string
	ContentWarnings       []string
	ContentRights         *model.ContentRights
	DistributionPolicy    *model.DistributionPolicy
	MetadataConfiguration *streamplace.MetadataConfiguration
	Livestream            *streamplace.Livestream
}

var ErrMissingMetadata = errors.New("missing segment metadata")
var ErrInvalidMetadata = errors.New("invalid segment metadata")

func ParseSegmentAssertions(ctx context.Context, mani *c2patypes.Manifest) (*SegmentMetadata, error) {
	_, span := otel.Tracer("signer").Start(ctx, "ParseSegmentAssertions")
	defer span.End()
	var ass *c2patypes.ManifestAssertion
	for _, a := range mani.Assertions {
		if a.Label == StreamplaceMetadata {
			ass = &a
			break
		}
	}
	if ass == nil {
		return nil, ErrMissingMetadata
	}
	proc := ld.NewJsonLdProcessor()
	options := ld.NewJsonLdOptions("")
	flat, err := proc.Expand(ass.Data, options)
	if err != nil {
		return nil, err
	}
	bs, err := json.Marshal(flat)
	if err != nil {
		return nil, err
	}
	var metas ExpandedSchemaOrg
	err = json.Unmarshal(bs, &metas)
	if err != nil {
		return nil, err
	}
	if len(metas) != 1 {
		return nil, ErrInvalidMetadata
	}
	meta := metas[0]
	if len(meta.Creator) == 0 {
		return nil, ErrInvalidMetadata
	}
	if len(meta.Title) != 1 {
		return nil, ErrInvalidMetadata
	}
	if len(meta.Date) != 1 {
		return nil, ErrInvalidMetadata
	}
	start, err := aqtime.FromString(meta.Date[0].Value)
	if err != nil {
		return nil, err
	}

	contentWarnings := extractContentWarnings(mani)
	contentRights := extractContentRights(mani)
	distributionPolicy := extractDistributionPolicy(mani, start)
	metadataConfiguration := extractMetadataConfiguration(mani)
	livestream := extractLivestream(mani)

	out := SegmentMetadata{
		StartTime:             start,
		Title:                 meta.Title[0].Value,
		Creator:               meta.Creator[0].Value,
		ContentWarnings:       contentWarnings,
		ContentRights:         contentRights,
		DistributionPolicy:    distributionPolicy,
		MetadataConfiguration: metadataConfiguration,
		Livestream:            livestream,
	}
	return &out, nil
}

// findAssertion finds an assertion by label
func findAssertion(mani *c2patypes.Manifest, label string) *c2patypes.ManifestAssertion {
	for _, a := range mani.Assertions {
		if a.Label == label {
			return &a
		}
	}
	return nil
}

// extractContentWarnings extracts content warnings from the C2PA manifest
func extractContentWarnings(mani *c2patypes.Manifest) []string {
	ass := findAssertion(mani, StreamplaceMetadata)
	if ass == nil {
		return nil
	}

	data, ok := ass.Data.(map[string]interface{})
	if !ok {
		return nil
	}

	warnings, ok := data["Iptc4xmpExt:ContentWarning"]
	if !ok {
		return nil
	}

	warningList, ok := warnings.([]interface{})
	if !ok {
		return nil
	}

	result := make([]string, 0, len(warningList))
	for _, warning := range warningList {
		if warningStr, ok := warning.(string); ok {
			result = append(result, warningStr)
		}
	}

	return result
}

// extractContentRights extracts content rights from the C2PA manifest
func extractContentRights(mani *c2patypes.Manifest) *model.ContentRights {
	ass := findAssertion(mani, StreamplaceMetadata)
	if ass == nil {
		return nil
	}

	data, ok := ass.Data.(map[string]interface{})
	if !ok {
		return nil
	}

	rights := &model.ContentRights{}

	// Extract copyright notice
	if notice, ok := data["dc:rights"]; ok {
		if noticeStr, ok := notice.(string); ok {
			rights.CopyrightNotice = &noticeStr
		}
	}

	// Extract copyright year
	if year, ok := data["Iptc4xmpExt:CopyrightYear"]; ok {
		if yearNum, ok := year.(float64); ok {
			yearInt := int64(yearNum)
			rights.CopyrightYear = &yearInt
		}
	}

	// Extract creator
	if creator, ok := data["dc:creator"]; ok {
		if creatorStr, ok := creator.(string); ok {
			rights.Creator = &creatorStr
		}
	}

	// Extract credit line
	if credit, ok := data["photoshop:Credit"]; ok {
		if creditStr, ok := credit.(string); ok {
			rights.CreditLine = &creditStr
		}
	}

	// Extract license information
	if license, ok := data["Iptc4xmpExt:LinkedEncRightsExpr"]; ok {
		if licenseStr, ok := license.(string); ok {
			rights.License = &licenseStr
		}
	} else if usageTerms, ok := data["xmpRights:UsageTerms"]; ok {
		if usageStr, ok := usageTerms.(string); ok {
			rights.License = &usageStr
		}
	}

	// Return nil if no rights information was found
	if rights.CopyrightNotice == nil && rights.CopyrightYear == nil &&
		rights.Creator == nil && rights.CreditLine == nil && rights.License == nil {
		return nil
	}

	return rights
}

// extractDistributionPolicy extracts distribution policy from the C2PA manifest
func extractDistributionPolicy(mani *c2patypes.Manifest, segmentStart aqtime.AQTime) *model.DistributionPolicy {
	ass := findAssertion(mani, StreamplaceMetadata)
	if ass == nil {
		return nil
	}

	data, ok := ass.Data.(map[string]interface{})
	if !ok {
		return nil
	}

	policy, ok := data["distributionPolicy"]
	if !ok {
		return nil
	}

	policyMap, ok := policy.(map[string]interface{})
	if !ok {
		return nil
	}

	expiry, ok := policyMap["deleteAfter"]
	if !ok {
		return nil
	}

	// deleteAfter now contains a timestamp string (RFC3339/ISO 8601 format)
	expiryStr, ok := expiry.(string)
	if !ok {
		return nil
	}

	expiryTime, err := time.Parse(time.RFC3339, expiryStr)
	if err != nil {
		return nil
	}

	return &model.DistributionPolicy{
		ExpiresAt: &expiryTime,
	}
}

// extractDistributionPolicy extracts the place.stream.metadata.configuration from the C2PA manifest
func extractMetadataConfiguration(mani *c2patypes.Manifest) *streamplace.MetadataConfiguration {
	ass := findAssertion(mani, "place.stream.metadata.configuration")
	if ass == nil {
		return nil
	}

	bs, err := json.Marshal(ass.Data)
	if err != nil {
		return nil
	}
	var metadataConfiguration streamplace.MetadataConfiguration
	err = json.Unmarshal(bs, &metadataConfiguration)
	if err != nil {
		return nil
	}
	return &metadataConfiguration
}

func extractLivestream(mani *c2patypes.Manifest) *streamplace.Livestream {
	ass := findAssertion(mani, "place.stream.livestream")
	if ass == nil {
		return nil
	}
	bs, err := json.Marshal(ass.Data)
	if err != nil {
		return nil
	}

	var livestream streamplace.Livestream
	err = json.Unmarshal(bs, &livestream)
	if err != nil {
		return nil
	}
	return &livestream
}
